def cd():
    print("Command : cd")
    print()
    print("Calling the cd command will change the current working directory to the path or directory specified <path>.")
    print()
    print("Usage: Type cd <path>")
    print()
    print("<path> is the name of directory or full path to change the working directory to.")
    print()
    print("If <path> is not specified, the current working directory will be displayed.")
    print()
    print("Example usage: Typing \'cd ..\' will change the current working directory to the parent directory.")
    print()
def clr():
    print("Command : clr")
    print()
    print("Calling the clr command will clear the terminal.")
    print()
    print("Usage: Type clr")
    print()
    print("No arguments required.")
    print()
def quit():
    print("Command : quit")
    print("")
    print("Usage: quit")
    print()
    print("Closes the SHELL program. Requires no arguments.")
    print("")
def dir():
    print("Command : dir")
    print()
    print("Calling the dir command will display all the files within <directory>.")
    print()
    print("Usage: Type dir <directory>")
    print()
    print("<directory> is the full path to directory to display the contents of.")
    print()
def echo():
    print("Command : echo")
    print()
    print("Usage: Type \'echo <message>\'",end="\n")
    print()
    print("<message> is any number of arguments passed to the echo command.")
    print()
    print("All arguments written after the \'echo\' command will be treated as words which will then be displayed on the terminal.")
    print()
    print("Multiple tabs and whitespaces will be treated as a single whitespace.")
    print()
def environ():
    print("Command : environ")
    print()
    print("Calling the environ command will display the environment variables and their path.")
    print()
    print("Usage: Type environ <variable>")
    print()
    print("<variable> name of environment variable's path to be displayed. Can be left blank to display all environment variables and path associated with them.")
    print()
def pause():
    print("Command : pause")
    print()
    print("Calling the pause command will temporary halt the function of shell commands.")
    print()
    print("Usage: Type pause")
    print()
    print("No arguments required")
    print()
    print("To exit pause mode, press enter on an empty line (no arguments before pressing enter).")
    print()
def help():
    print("Command : help")
    print()
    print("Display the built in commands within the shell.")
    print()
    print("Usage: Type help <command> ")
    print()
    print("<command> is one of the built in commands of the shell.")
    print()
def more():
    border = "--------------------------------------------------------------"
    cd()
    print(border)
    clr()
    print(border)
    quit()
    print(border)
    dir()
    print(border)
    echo()
    print(border)
    environ()
    print(border)
    pause()
    print(border)
    help()